name: Export Error Messages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events.
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export:
    name: Export Error Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Find .sln file
        id: findSlnFile        
        run: |
          echo solutionFilePath=$(find . -type f -name '*.sln') >> $GITHUB_OUTPUT
        shell: bash  
      
      - name: Building
        run: dotnet build "${{ steps.findSlnFile.outputs.solutionFilePath }}" --configuration Release -nodeReuse:false

      - name: Run export logic
        run: ./ExportErrorMessages.ps1 -version ${{ github.ref_name }} -outputDir "${{ github.workspace }}/Error Messages"

      - uses: actions/upload-artifact@v4
        with:
          name: Error Messages
          path: "${{ github.workspace }}/Error Messages"
